version = 1

exclude_patterns = ["migrations/**"]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = [
  "requirements.txt",
]

  [analyzers.meta]
  runtime_version = "3.x.x"
  type_checker = "mypy"
