"""Add options for mcqs

Revision ID: 268963198b7e
Revises: 9af6cc354099
Create Date: 2020-03-17 16:24:19.024507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268963198b7e'
down_revision = '9af6cc354099'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('option1', sa.Text(), nullable=True))
    op.add_column('question', sa.Column('option2', sa.Text(), nullable=True))
    op.add_column('question', sa.Column('option3', sa.Text(), nullable=True))
    op.add_column('question', sa.Column('option4', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'option4')
    op.drop_column('question', 'option3')
    op.drop_column('question', 'option2')
    op.drop_column('question', 'option1')
    # ### end Alembic commands ###
