"""Initial Migration

Revision ID: 29d5d2d8a67f
Revises: 
Create Date: 2020-03-11 11:36:13.451848

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '29d5d2d8a67f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('question', sa.Text(), nullable=False),
                    sa.Column('mark', sa.Integer(), nullable=False),
                    sa.Column('difficulty', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    # ### end Alembic commands ###
