"""Migration message

Revision ID: 3aad4820813b
Revises: 5984a6227db9
Create Date: 2020-06-16 17:04:26.718016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aad4820813b'
down_revision = '5984a6227db9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('include_asked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'include_asked')
    # ### end Alembic commands ###
