"""Added boolean field for mcq

Revision ID: 7f383df53087
Revises: 268963198b7e
Create Date: 2020-03-27 12:09:08.544989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f383df53087'
down_revision = '268963198b7e'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('is_mcq', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'is_mcq')
    # ### end Alembic commands ###
