"""Migration message

Revision ID: 9af6cc354099
Revises: 29d5d2d8a67f
Create Date: 2020-03-16 20:56:58.960433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9af6cc354099'
down_revision = '29d5d2d8a67f'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('imp', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'imp')
    # ### end Alembic commands ###
